name: ArtLift Bot (Playwright)

on:
  schedule:
    # 15 exécutions/jour : 05:05–19:05 UTC = 07:05–21:05 Bruxelles (CEST)
    - cron: "5 5-19 * * *"
  workflow_dispatch:

concurrency:
  group: artlift-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (optionnel mais utile) Cache le navigateur Playwright entre les runs
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-firefox
          restore-keys: playwright-

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps firefox

      - name: Anti-burst jitter
        run: sleep $((RANDOM % 600))  # 0–10 min

      - name: Post
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
        run: python main.py

      # === DEBUG: récupère les captures *.png générées par main.py ===
      # Retire ce bloc quand tout est stable
      - name: Upload screenshots (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screens
          path: |
            *.png
