name: ArtLift Bot (Bluesky)

on:
  schedule:
    # Matin Bruxelles ≈ 07–09 -> UTC ≈ 05–07
    - cron: "15 5,6,7 * * *"
    # Soir Bruxelles ≈ 19–22 -> UTC ≈ 17–20
    - cron: "10 17,18,19,20 * * *"
  workflow_dispatch:

concurrency:
  group: artlift-bot-bsky
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Anti-burst jitter
        run: sleep $((RANDOM % 300))  # 0–5 min

      - name: Run ArtLift Bluesky
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          # Si tu veux forcer un mode selon la tranche, commente ceci
          # MODE: morning_likes   # ou evening_posts
        run: python main_bsky.py
