name: ArtLift Bot (Bluesky)

on:
  schedule:
    # Matin Bruxelles ~ 07–11 -> UTC 05–09
    - cron: "7 5,6,7,8,9 * * *"
    # Soir Bruxelles ~ 19–22 -> UTC 17–20
    - cron: "12 17,18,19,20 * * *"
  workflow_dispatch:

concurrency:
  group: artlift-bot-bsky
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: List repo files (sanity)
        run: |
          pwd
          ls -la
          ls -la scripts || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Anti-burst jitter
        run: sleep $((RANDOM % 300))

      # A) si main_bsky.py est à la racine :
      - name: Run ArtLift Bluesky
        if: ${{ hashFiles('main_bsky.py') != '' }}
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: python main_bsky.py

      # B) si ton script est dans scripts/
      - name: Run ArtLift Bluesky (scripts/)
        if: ${{ hashFiles('scripts/main_bsky.py') != '' }}
        working-directory: scripts
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: python main_bsky.py
