name: ArtLift Bot

on:
  schedule:
    # GitHub cron est en UTC. Ici: 05 à 19 UTC = 07:00→21:00 heure de Bruxelles (CEST, UTC+2).
    - cron: "5 5-19 * * *"
  workflow_dispatch:

concurrency:
  group: artlift-bot
  cancel-in-progress: false

jobs:
  post:
    runs-on: ubuntu-latest  # Linux = minutes gratuites en public, 1× en privé
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Jitter (anti-rafale)
        run: sleep $((RANDOM % 600))  # 0–10 minutes

      - name: Run bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py
